package com.example.accessingdatamysql.service;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.example.accessingdatamysql.model.Student;
import com.example.accessingdatamysql.service.repo.StudentRepository;
import com.example.accessingdatamysql.service.repo.entity.StudentEntity;

@Service    
public class RegisterService {

	@Autowired // This means to get the bean called userRepository which is auto-generated by Spring, we will use it to handle the data
    private StudentRepository studentRepository;

    public Register save(Register register) {
        RegisterEntity registerEntity = new RegisterEntity();
		registerEntity.setStudentID(register.getStudentID());
		registerEntity.setCourse1(register.getCourse1());
		registerEntity.setCourse2(register.getCourse2());                                      // 0: Expired, 1: Active (Default)
		registerEntity.setCourse3(register.getCourse3());
        registerEntity.setCourse4(register.getCourse4());
        registerEntity.setCourse5(register.getCourse5());


		RegisterEntity resultRegisterEntity = studentRepository.save(registerEntity);


        Register resultRegister = new Register();

        resultRegister.setStudentID(resultRegisterEntity.getStudentID());
		resultRegister.setCourse1(resultRegisterEntity.getCourse1());
		resultRegister.setCourse2(resultRegisterEntity.getCourse2());                                      // 0: Expired, 1: Active (Default)
		resultRegister.setCourse3(resultRegisterEntity.getCourse3());
        resultRegister.setCourse4(resultRegisterEntity.getCourse4());
        resultRegister.setCourse5(resultRegisterEntity.getCourse5());

        return resultRegister;
    }
}