package com.example.accessingdatamysql.service;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.example.accessingdatamysql.model.Register;
import com.example.accessingdatamysql.service.repo.RegisterRepository;
import com.example.accessingdatamysql.service.repo.entity.RegisterEntity;

@Service    
public class RegisterService {

	@Autowired // This means to get the bean called userRepository which is auto-generated by Spring, we will use it to handle the data
    private RegisterRepository registerRepository;

    public Register save(Register register) {
        RegisterEntity registerEntity = new RegisterEntity();
		registerEntity.setStudentId(register.getStudentId());
		registerEntity.setCourseId1(register.getCourseid1());
		registerEntity.setCourseId2(register.getCourseid2());                                      // 0: Expired, 1: Active (Default)
		registerEntity.setCourseId3(register.getCourseid3());
        registerEntity.setCourseId4(register.getCourseid4());
        registerEntity.setCourseId5(register.getCourseid5());


		RegisterEntity resultRegisterEntity = registerRepository.save(registerEntity);


        Register resultRegister = new Register();

        resultRegister.setStudentId(resultRegisterEntity.getStudentId());
		resultRegister.setCourseid1(resultRegisterEntity.getCourseId1());
		resultRegister.setCourseid2(resultRegisterEntity.getCourseId2());                                      // 0: Expired, 1: Active (Default)
		resultRegister.setCourseid3(resultRegisterEntity.getCourseId3());
        resultRegister.setCourseid4(resultRegisterEntity.getCourseId4());
        resultRegister.setCourseid5(resultRegisterEntity.getCourseId5());

        return resultRegister;
    }
}